twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    globals:
        paths_url: 'https://openclassrooms.com/fr/paths'
        mentor_dashboard_url: 'https://openclassrooms.com/fr/mentorship/dashboard'
        student_dashboard_url: 'https://openclassrooms.com/fr/mentorship/students/{idOC}/dashboard'